INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("3 (tie)","Actuarial Science","Bachelor's","60800","119000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("11 (tie)","Physics & Mathematics","Bachelor's","56200","111000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("15 (tie)","Physics","Bachelor's","55100","108000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("19 (tie)","Computer Science (CS)","Bachelor's","65300","107000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("24","Government","Bachelor's","49600","105000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("28 (tie)","Physician Assistant Studies","Bachelor's","85200","103000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("32","Economics","Bachelor's","53900","100000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("37 (tie)","Biochemistry & Molecular Biology","Bachelor's","46000","97500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("37 (tie)","Statistics","Bachelor's","57400","97500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("42","Mathematics","Bachelor's","54000","95700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("43","Computing","Bachelor's","51400","95500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("44","Mathematics & Statistics","Bachelor's","53700","95300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("60","Government & Politics","Bachelor's","44600","90400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("61","Aviation Management","Bachelor's","41900","90200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("62","Molecular Biology","Bachelor's","45500","90100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("64 (tie)","Environmental Health & Safety","Bachelor's","51200","89800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("67","Computer Information Systems (CIS)","Bachelor's","54300","89500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("69","Industrial Management","Bachelor's","51600","88200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("70 (tie)","Telecommunications Management","Bachelor's","50000","87500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("73","Information Systems Management","Bachelor's","54000","87200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("74 (tie)","Information Technology (IT) & Systems","Bachelor's","52800","87100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("74 (tie)","Telecommunications","Bachelor's","40800","87100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("76","Information Technology Management","Bachelor's","53700","86800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("78","Physical Therapy","Bachelor's","60300","86600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("79 (tie)","International Relations","Bachelor's","46500","86400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("82 (tie)","Information Security","Bachelor's","58300","85600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("86","Technical Communication","Bachelor's","45300","85100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("90 (tie)","Organizational Behavior","Bachelor's","47000","84400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("92 (tie)","Information Technology (IT)","Bachelor's","53000","84300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("92 (tie)","Politics","Bachelor's","45600","84300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("95","Philosophy","Bachelor's","44700","84100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("97","Industrial Technology (IT)","Bachelor's","55200","83400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("98 (tie)","Public Affairs","Bachelor's","46800","83100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("100 (tie)","Biochemistry (BCH)","Bachelor's","44700","83000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("100 (tie)","Chemistry","Bachelor's","45700","83000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("103","Computer Information Systems","Bachelor's","47100","82800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("104","Meteorology","Bachelor's","43600","82700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("107 (tie)","Industrial Design (ID)","Bachelor's","48600","82100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("107 (tie)","Occupational Health and Safety","Bachelor's","54900","82100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("110","Pre-Medicine","Bachelor's","42700","81200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("111","Food Science","Bachelor's","46700","81100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("114","Food Science & Technology","Bachelor's","49000","80400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("115 (tie)","Biology & Chemistry","Bachelor's","41500","79900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("115 (tie)","Political Science (PolySci)","Bachelor's","44300","79900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("117 (tie)","Geology","Bachelor's","44800","79800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("120 (tie)","Architecture","Bachelor's","45100","79300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("120 (tie)","Microbiology","Bachelor's","44600","79300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("122","Biological Sciences","Bachelor's","42900","79200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("126","Urban & Regional Planning","Bachelor's","44000","78100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("127 (tie)","Fashion Design","Bachelor's","41400","77700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("132 (tie)","Environmental Design","Bachelor's","42900","77200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("134","Organizational Development","Bachelor's","52800","77100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("135","Environmental Science","Bachelor's","43300","77000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("137","Logistics","Bachelor's","51500","76500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("138","Technology Management","Bachelor's","52500","76400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("139","History & Political Science","Bachelor's","44500","76000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("142 (tie)","Dental Hygiene","Bachelor's","65400","74900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("142 (tie)","Industrial Psychology","Bachelor's","44000","74900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("144 (tie)","Aeronautics","Bachelor's","53900","74600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("146","Agronomy","Bachelor's","45600","74400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("147","English Literature","Bachelor's","41100","74300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("148 (tie)","Digital Media","Bachelor's","40800","74200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("148 (tie)","Environmental Studies","Bachelor's","41500","74200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("148 (tie)","Foreign Languages","Bachelor's","42500","74200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("148 (tie)","Information Systems Security","Bachelor's","57100","74200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("152","Nursing","Bachelor's","57500","74100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("153","Landscape Architecture","Bachelor's","44400","74000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("155","History","Bachelor's","42200","73600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("156 (tie)","Film Production","Bachelor's","41400","73500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("156 (tie)","Literature","Bachelor's","40400","73500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("158","Biology","Bachelor's","40800","73100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("160","Computer Aided Drafting & Design (CADD)","Bachelor's","43300","72800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("161","Design","Bachelor's","42400","72700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("162","General Science","Bachelor's","41600","72600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("164 (tie)","American Studies","Bachelor's","45100","72400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("167 (tie)","Communication","Bachelor's","42100","72300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("167 (tie)","Theatre & Drama Studies","Bachelor's","40400","72300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("167 (tie)","Urban Studies","Bachelor's","44500","72300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("171 (tie)","Communication Studies & Journalism","Bachelor's","39800","72100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("171 (tie)","Interior Architecture","Bachelor's","43200","72100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("173","Computer Networking Systems","Bachelor's","46900","71900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("174 (tie)","German Language & Literature","Bachelor's","44400","71700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("174 (tie)","International Studies","Bachelor's","43300","71700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("176","Pre-law","Bachelor's","42300","71300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("177","Public Relations & Communication","Bachelor's","39800","71200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("178","Diagnostic Medical Sonography","Bachelor's","57700","71100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("179 (tie)","French Language","Bachelor's","43900","71000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("179 (tie)","Journalism & Mass Communication","Bachelor's","41100","71000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("182","Public Relations (PR)","Bachelor's","40100","70700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("183","Speech Communication","Bachelor's","42000","70600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("185","Environmental Biology","Bachelor's","40900","70400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("186","Film Studies","Bachelor's","39800","70000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("187","American History (United States)","Bachelor's","42000","69600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("188","Journalism","Bachelor's","41200","69400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("189","Environmental Management","Bachelor's","47400","69300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("190","Marketing & Mass Communications","Bachelor's","40600","69000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("191 (tie)","Broadcast Communication","Bachelor's","35600","68700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("191 (tie)","Geographic Information Systems (GIS)","Bachelor's","44900","68700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("191 (tie)","Natural Resource Management","Bachelor's","39500","68700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("194 (tie)","English Language & Literature","Bachelor's","40400","68200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("194 (tie)","Geography","Bachelor's","43800","68200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("197","Nuclear Medicine Technology","Bachelor's","55200","67900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("198","Linguistics","Bachelor's","44500","67800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("199","Technical Theatre","Bachelor's","35100","67700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("200","Agriculture","Bachelor's","40800","67600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("202","Forestry","Bachelor's","41500","67400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("203","Zoology","Bachelor's","35600","67300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("204","Advertising & Graphic Design","Bachelor's","42400","67100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("205","Writing","Bachelor's","38000","67000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("206","Computer & Network Administration","Bachelor's","50800","66900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("208","International Affairs","Bachelor's","44200","66600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("209","Multimedia & Web Design","Bachelor's","42300","66500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("210 (tie)",""Film, Video & Media Studies"","Bachelor's","39600","66300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("210 (tie)","Mass Communication","Bachelor's","40200","66300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("214","Radio/Television & Film Production","Bachelor's","40700","66200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("215","Public Administration","Bachelor's","40900","66100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("216","Radiologic Technology","Bachelor's","45100","66000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("217","Creative Writing","Bachelor's","38900","65900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("218","Media Communication","Bachelor's","39400","65500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("219 (tie)","Leadership","Bachelor's","47100","65300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("219 (tie)","Organizational Leadership","Bachelor's","43900","65300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("221","Sports Management","Bachelor's","39100","65200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("222 (tie)","Cultural Anthropology","Bachelor's","41000","65000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("222 (tie)","Music Performance","Bachelor's","39900","65000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("222 (tie)","Organizational Communication","Bachelor's","41400","65000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("225","Radio & Television","Bachelor's","38000","64300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("226","Broadcast Journalism","Bachelor's","38400","64200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("227","Medical Laboratory Technology","Bachelor's","48500","64000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("228","Criminal Justice Administration","Bachelor's","39000","63900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("229 (tie)","Health Information Management","Bachelor's","41700","63800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("229 (tie)","Visual Arts (VA)","Bachelor's","39600","63800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("231","Secondary English Teacher Education","Bachelor's","37800","63700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("232 (tie)","Criminology","Bachelor's","39500","63600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("232 (tie)","Spanish Language","Bachelor's","40300","63600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("234","Art History","Bachelor's","40800","63300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("235","Fashion Merchandising","Bachelor's","41200","63000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("236","Respiratory Therapy","Bachelor's","46200","62900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("237 (tie)","Hotel & Restaurant Management","Bachelor's","41000","62800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("237 (tie)","Illustration","Bachelor's","39000","62800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("239 (tie)","Clinical Laboratory Science","Bachelor's","48800","62700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("239 (tie)",""Hotel, Restaurant, and Institutional Management (HRIM)"","Bachelor's","50500","62700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("241 (tie)","Art & Design","Bachelor's","39500","62600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("241 (tie)","Health Sciences","Bachelor's","38300","62600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("243 (tie)","Fine Arts","Bachelor's","38400","62500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("243 (tie)","Visual Communication Design","Bachelor's","40700","62500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("246","Visual Communications","Bachelor's","40500","62400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("247 (tie)","Liberal Arts","Bachelor's","39100","62300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("247 (tie)","Sociology","Bachelor's","40400","62300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("249","Hospitality & Tourism","Bachelor's","37900","62200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("250 (tie)","Communication Design","Bachelor's","45300","62100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("250 (tie)","Psychology","Bachelor's","38300","62100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("252","Kinesiology","Bachelor's","37800","61800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("253","Nutrition","Bachelor's","40700","61600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("254","Medical Laboratory Science","Bachelor's","47900","61500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("256","Interior Design","Bachelor's","39600","61000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("257","Health","Bachelor's","35700","60700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("258","Studio Art","Bachelor's","36700","60600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("259 (tie)","Anthropology","Bachelor's","39900","60500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("259 (tie)","Dietetics","Bachelor's","44300","60500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("259 (tie)","Graphic Design","Bachelor's","40000","60500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("259 (tie)","Public Health (PH)","Bachelor's","38300","60500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("263 (tie)","Exercise Physiology","Bachelor's","38400","60300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("263 (tie)","Religious Studies","Bachelor's","38500","60300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("265","Hospitality Management","Bachelor's","40500","60200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("267 (tie)","Music Business","Bachelor's","39100","60000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("267 (tie)","Social Science","Bachelor's","39700","60000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("269 (tie)","Health Care Administration","Bachelor's","39400","59900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("269 (tie)","Theater","Bachelor's","39500","59900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("271","Interdisciplinary Studies (IS)","Bachelor's","39800","59500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("272","Human Resources Development","Bachelor's","40400","59400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("273",""Graphic Design, Illustration"","Bachelor's","36800","59300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("274 (tie)","Criminal Justice","Bachelor's","37000","59100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("274 (tie)","Nutrition & Dietetics","Bachelor's","44000","59100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("276","Health Administration","Bachelor's","36600","59000");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("277 (tie)","Animal Science","Bachelor's","35800","58900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("277 (tie)","Exercise & Sports Science","Bachelor's","36800","58900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("279 (tie)","Foods & Nutrition","Bachelor's","40900","58700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("279 (tie)","Painting","Bachelor's","37200","58700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("279 (tie)","Photography","Bachelor's","38000","58700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("282","Liberal Studies","Bachelor's","39600","58600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("283","Restaurant & Food Service Management","Bachelor's","40600","58400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("284 (tie)","Music","Bachelor's","38300","58300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("284 (tie)","Theatre","Bachelor's","36500","58300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("286 (tie)","Practical Nursing","Bachelor's","45300","58100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("286 (tie)","Social & Criminal Justice","Bachelor's","40800","58100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("289 (tie)","Legal Studies","Bachelor's","40200","57800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("291","Administration","Bachelor's","39500","57600");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("292 (tie)","Graphic Communication","Bachelor's","40500","57300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("294 (tie)","Humanities","Bachelor's","40900","57200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("294 (tie)","Psychology & Sociology","Bachelor's","37800","57200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("296","Media Arts","Bachelor's","39600","57100");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("297","Family & Consumer Science","Bachelor's","35900","56500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("298 (tie)","Art","Bachelor's","36500","56400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("298 (tie)","Religion","Bachelor's","37800","56400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("300 (tie)","Behavioral Science","Bachelor's","35800","56200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("300 (tie)","Recreation Management","Bachelor's","37800","56200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("302","Human Development","Bachelor's","36700","55900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("303","Communication Arts","Bachelor's","40000","55800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("305","Health Care Management","Bachelor's","37800","55500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("306","Culinary Arts","Bachelor's","33100","55300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("307 (tie)","Culinary Arts & Culinary Management","Bachelor's","33600","55200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("309 (tie)","Paralegal Studies","Bachelor's","35200","54900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("309 (tie)","Theatre Arts","Bachelor's","37200","54900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("311 (tie)","Dance","Bachelor's","38200","54800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("311 (tie)","Women's Studies","Bachelor's","40400","54800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("313","Exercise Science","Bachelor's","35900","54700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("314 (tie)","General Studies","Bachelor's","38700","54300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("314 (tie)","Recreation & Leisure Studies","Bachelor's","39000","54300");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("316","Athletic Training","Bachelor's","36000","51900");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("317","Parks & Recreation Management","Bachelor's","38200","51700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("318 (tie)","Health Services Administration","Bachelor's","36300","51500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("321","Theology","Bachelor's","37600","51200");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("322 (tie)","Culinary Arts & Food Service Management","Bachelor's","34700","50500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("322 (tie)","Horticulture","Bachelor's","37600","50500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("322 (tie)","Pastoral Ministry","Bachelor's","32800","50500");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("325","Bible Studies & Theology","Bachelor's","34900","50400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("326","Biblical Studies","Bachelor's","36200","49400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("328","Youth Ministry","Bachelor's","32900","48400");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("329","Human Development & Family Studies","Bachelor's","34300","47800");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("330","Therapeutic Recreation","Bachelor's","35200","47700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("331","Social Work (SW)","Bachelor's","33800","46700");
INSERT INTO `Arts_and_Science`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("332","Human Services (HS)","Bachelor's","34000","44600");
