INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("31","Finance & Real Estate","Bachelor's","59500","101000");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("35","Finance & Economics","Bachelor's","56700","98200");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("39","Management Information Systems (MIS)","Bachelor's","58100","97400");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("45","Management Science","Bachelor's","57200","95000");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("46","Marketing & International Business","Bachelor's","45400","94800");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("48","Construction Management","Bachelor's","57400","94500");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("52","Business Information Systems","Bachelor's","56300","92600");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("53 (tie)","Information Systems (IS)","Bachelor's","56300","92200");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("53 (tie)","Operations & Supply Chain Management","Bachelor's","52600","92200");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("56 (tie)","International Business","Bachelor's","48800","91000");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("66","Finance","Bachelor's","53300","89600");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("68","Informatics","Bachelor's","60100","88800");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("70 (tie)","Business Economics","Bachelor's","52100","87500");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("77","Agricultural Economics & Business","Bachelor's","44600","86700");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("79 (tie)","Accounting & Finance","Bachelor's","52800","86400");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("81","Operations Management (OM)","Bachelor's","54800","86200");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("84","Business & Marketing","Bachelor's","45800","85300");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("88","Marketing & Management","Bachelor's","44700","84800");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("89","Real Estate","Bachelor's","55400","84500");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("90 (tie)","Supply Chain Management","Bachelor's","54500","84400");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("98 (tie)","Agribusiness","Bachelor's","43200","83100");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("100 (tie)","Business Management & Marketing","Bachelor's","45000","83000");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("106","Marketing","Bachelor's","45300","82500");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("109","Financial Accounting","Bachelor's","45100","82000");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("112","Sales & Marketing","Bachelor's","45400","80800");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("113","Risk Management & Insurance","Bachelor's","52300","80600");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("117 (tie)","Advertising","Bachelor's","41400","79800");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("117 (tie)","Advertising & Marketing Communications","Bachelor's","43400","79800");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("123","Marketing & Communications","Bachelor's","44900","79000");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("124","Transportation & Logistics Management","Bachelor's","47800","78900");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("125","Marketing Management","Bachelor's","45300","78500");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("127 (tie)","Project Management","Bachelor's","49500","77700");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("129","Logistics & Supply Chain Management","Bachelor's","51800","77400");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("130 (tie)","Financial Management","Bachelor's","49300","77300");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("130 (tie)","Law","Bachelor's","47600","77300");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("132 (tie)","Accounting","Bachelor's","48300","77200");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("136","Business Communication","Bachelor's","44400","76600");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("140","Finance & Banking","Bachelor's","48600","75900");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("141","Technical Management","Bachelor's","46300","75700");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("144 (tie)","Entrepreneurship","Bachelor's","48000","74600");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("154","General Business","Bachelor's","45000","73900");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("159","Management","Bachelor's","45000","73000");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("163","Business Management & Human Resources Management (HRM)","Bachelor's","42100","72500");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("164 (tie)","Business Administration","Bachelor's","46100","72400");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("164 (tie)","Professional & Technical Writing","Bachelor's","42700","72400");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("167 (tie)","Business Management","Bachelor's","45800","72300");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("181","Accounting & Management","Bachelor's","48700","70800");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("184","Accounting & Business","Bachelor's","45200","70500");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("196","Human Resources Management (HRM)","Bachelor's","42300","68100");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("201","Business Administration & Accounting","Bachelor's","44900","67500");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("207","Business Management & Administration","Bachelor's","46100","66700");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("210 (tie)","Human Resources (HR)","Bachelor's","41900","66300");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("210 (tie)","Organizational Management","Bachelor's","44000","66300");
INSERT INTO `Business`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("243 (tie)","Business & Healthcare Management","Bachelor's","40000","62500");
