INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("1","Petroleum Engineering","Bachelor's","96700","172000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("2","Systems Engineering","Bachelor's","66400","121000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("3 (tie)","Chemical Engineering","Bachelor's","69800","119000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("5 (tie)","Computer Science (CS) & Engineering","Bachelor's","71200","116000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("5 (tie)","Nuclear Engineering","Bachelor's","68500","116000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("7","Electronics & Communications Engineering","Bachelor's","68000","115000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("8","Electrical & Computer Engineering (ECE)","Bachelor's","68100","114000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("9 (tie)","Aeronautical Engineering","Bachelor's","63000","113000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("9 (tie)","Computer Engineering (CE)","Bachelor's","69600","113000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("11 (tie)","Computer Science (CS) & Mathematics","Bachelor's","63500","111000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("13 (tie)","Applied Mathematics","Bachelor's","56100","110000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("13 (tie)","Electrical Engineering (EE)","Bachelor's","67000","110000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("15 (tie)","Electrical & Electronics Engineering (EEE)","Bachelor's","64000","108000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("15 (tie)","Industrial & Systems Engineering","Bachelor's","63800","108000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("15 (tie)","Materials Science & Engineering","Bachelor's","65800","108000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("19 (tie)","Engineering","Bachelor's","62600","107000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("19 (tie)","Industrial Distribution","Bachelor's","56800","107000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("19 (tie)","Mining Engineering","Bachelor's","70200","107000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("23","Aerospace Engineering","Bachelor's","65400","106000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("25 (tie)","Biomedical Engineering (BME)","Bachelor's","62700","104000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("25 (tie)","Industrial Engineering (IE)","Bachelor's","63800","104000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("25 (tie)","Structural Engineering (SE)","Bachelor's","58700","104000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("28 (tie)","Mechanical Engineering (ME)","Bachelor's","63500","103000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("30","Construction Engineering Management","Bachelor's","59500","102000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("33","Electronics Engineering","Bachelor's","61300","99600");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("34","Engineering Management","Bachelor's","62800","98400");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("36","Software Engineering","Bachelor's","64700","98100");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("40","Building Construction Management","Bachelor's","54400","96500");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("41","Civil Engineering (CE)","Bachelor's","57200","96300");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("47","Packaging Science","Bachelor's","61100","94600");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("49","Building Construction (BC)","Bachelor's","56000","94000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("50","Manufacturing Engineering","Bachelor's","62000","93200");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("51","Environmental Engineering","Bachelor's","53900","92800");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("55","Civil & Environmental Engineering","Bachelor's","57200","91100");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("56 (tie)","Construction Engineering","Bachelor's","59800","91000");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("58","Engineering Technology (ET)","Bachelor's","52500","90800");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("59","Agricultural Engineering (AE)","Bachelor's","55000","90600");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("63","Electrical Engineering Technology (EET)","Bachelor's","59900","89900");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("64 (tie)","Architectural Engineering","Bachelor's","61700","89800");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("72","Mechanical Engineering Technology (MET)","Bachelor's","57600","87400");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("82 (tie)","Manufacturing Engineering Technology","Bachelor's","59100","85600");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("85","Construction Project Management","Bachelor's","52500","85200");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("87","Electronics Engineering Technology (EET)","Bachelor's","58100","84900");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("92 (tie)","Civil Engineering Technology (CET)","Bachelor's","51300","84300");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("96","Industrial Engineering Technology","Bachelor's","60100","83600");
INSERT INTO `Engineering`(`Ranking`, `Major`, `DegreeType`, `EarlyPay`, `MidPay`) VALUES ("105","Computer Programming","Bachelor's","50500","82600");
